/* Generated by MyraPad at 12/28/2024 2:14:00 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace PurplePuffin
{
	partial class OptionsMenuMyra: Panel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Purple Puffin - Options";
			label1.TextColor = ColorStorage.CreateColor(248, 255, 199, 255);
			label1.Top = 20;
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var label2 = new Label();
			label2.Text = "Music Volume";
			label2.TextColor = ColorStorage.CreateColor(248, 255, 199, 255);
			label2.Left = 80;

			_hsMusicVolume = new HorizontalSlider();
			_hsMusicVolume.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_hsMusicVolume.Width = 400;
			_hsMusicVolume.Tooltip = "Adjust the volume of music";
			_hsMusicVolume.Id = "_hsMusicVolume";

			var panel1 = new Panel();
			panel1.Top = 100;
			panel1.MinWidth = 0;
			panel1.Height = 200;
			panel1.Widgets.Add(label2);
			panel1.Widgets.Add(_hsMusicVolume);

			_menuBackToMainMenu = new MenuItem();
			_menuBackToMainMenu.Text = "Back to Main Menu";
			_menuBackToMainMenu.Id = "_menuBackToMainMenu";

			_optionsMenu = new VerticalMenu();
			_optionsMenu.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_optionsMenu.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_optionsMenu.LabelColor = ColorStorage.CreateColor(248, 255, 199, 255);
			_optionsMenu.SelectionHoverBackground = new SolidBrush("#3F1178C0");
			_optionsMenu.SelectionBackground = new SolidBrush("#711ED6C0");
			_optionsMenu.Border = new SolidBrush("#00000000");
			_optionsMenu.Id = "_optionsMenu";
			_optionsMenu.Items.Add(_menuBackToMainMenu);

			
			Background = new SolidBrush("#711ED6FF");
			Widgets.Add(label1);
			Widgets.Add(panel1);
			Widgets.Add(_optionsMenu);
		}

		
		public HorizontalSlider _hsMusicVolume;
		public MenuItem _menuBackToMainMenu;
		public VerticalMenu _optionsMenu;
	}
}
